### ISSUE TITLE
erase used while iterating through the map

### ISSUE THREAD

**Issue by fenbf** [sol-prog/cpp17-filewatcher#2] opened 2019-01-15 13:12 UTC
in your code you use `paths_.erase(el.first);`... but that might invalidate the iterator.

probably it's better to use while loop:
```
auto it = paths_.begin();
while (it != paths_.end())
{
    if (!std::filesystem::exists(it->first)) {
        action(it->first, FileStatus::erased);
        it = paths_.erase(it);
    }
    else
        it++;
}
```

**Comment by sol-prog** [comment] 2019-01-15 14:30
As far as I understand it, only the reference to the erased element is invalidated https://en.cppreference.com/w/cpp/container/unordered_map/erase so you can use a range for loop. What you shouldn't do is to try to the use object once erased. 

Also, I pass a copy of the string path to the user defined lambda function  https://github.com/sol-prog/cpp17-filewatcher/blob/master/test_fs_watcher.cpp#L15 before erasing the map element. I don't pass a reference to a map element.

Let me know if you think I'm wrong.

**Comment by fenbf** [comment] 2019-01-15 14:36
ok, so this should work in unordered_maps:
"The order of the elements that are not erased is preserved (this makes it possible to erase individual elements while iterating through the container) "
I changed it to std::map in my forked implementation and got AV at some point.

**Comment by sol-prog** [comment] 2019-01-15 14:39
Yes, I remember reading that I can safely erase elements from a std::unordered_map. I've also tested the code with various inputs and never had a crash. 

std::map will not work for this case.

**Comment by fenbf** [comment] 2019-04-14 21:11
sorry for bringing that up again :)
hmmm... there still might be a problem with this implementation. on VS 2017 it crashes

use case: run the app, add one file, wait till it appears in the console output as created, then delete that file and wait for the log message (app crashes)
so I had to change the implementation and use `it = map.erase(it)`

other sources like https://en.cppreference.com/w/cpp/container/unordered_map/erase or https://stackoverflow.com/questions/38468844/erasing-elements-from-unordered-map-in-a-loop/38469800 also mention that same pattern.

if you use `erase(it)` then it is invalidated and then incrementing it might give the error. Maybe in GCC/clang it behaves differently...

**Comment by sol-prog** [comment] 2019-04-14 21:40
<img width="924" alt="Screen Shot 2019-04-14 at 5 40 02 PM" src="https://user-images.githubusercontent.com/1109191/56099538-5a298f80-5edc-11e9-9890-2520e6483570.png">

**Comment by sol-prog** [comment] 2019-04-14 21:42
I would assume VS has a bug in this case if you can't erase the element while iterating. 

BTW, have you tried compiling with /std:c++17 or /std:c++latest ?

**Comment by fenbf** [comment] 2019-04-15 05:17
yes, I see, but there's also another sentence "References and iterators to the erased elements are invalidated. Other iterators and references are not invalidated."
so if you write `erase(it)` then `it` becomes invalidated... isn't it?
I compiled with stdc++17

**Comment by sol-prog** [comment] 2019-04-15 12:36
I may be wrong, but this is how I understand "References and iterators to the erased elements are invalidated. Other iterators and references are not invalidated."

Say you have some unordered map {a->x,b->y,c->z,d->r} and you have a reference to the second element b. Now, if you *erase* b while in a loop the reference to b will be invalidated but you should still be able to finish the loop without crashing. What I'm trying to say is that the iterator to the map should still be OK to use during the loop.

I'll do some tests later today and try to reproduce your crash.

**Comment by sol-prog** [comment] 2019-04-15 14:27
So, I was wrong :)

I did some tests with Visual Studio 2019 and you were right the app crashed when a file was removed. I can patch the code myself or you can send me a pull request if you prefer. Let me know how you want to proceed.

Thanks.

**Comment by fenbf** [comment] 2019-04-15 14:40
it's probably faster if you provide the code, thanks!

**Comment by sol-prog** [comment] 2019-04-15 14:50
Will do, just wanted to ask you if you had any problems with VS 2017 on this line for example:

https://github.com/sol-prog/cpp17-filewatcher/blob/master/FileWatcher.h#L50

because with VS 2019 I had to change it into something like this

```
if(paths_[file.path().string()] != current_file_last_write_time)
```

(Clang and GCC don't have any problem with the above.)

**Comment by sol-prog** [comment] 2019-04-15 15:36
OK, I've modified the code. Thanks for suggesting a solution, I've mentioned your contribution in the pull request.

**Closed as completed by sol-prog** 2019-04-15 15:36 UTC

**Comment by fenbf** [comment] 2019-04-15 18:46
ah, yes, I needed to add .string() calls as there's no implicit conversion from path to string in MSVC
why does it compile on GCC/clang?

**Comment by sol-prog** [comment] 2019-04-15 20:13
Yep, there was no problem under GCC 8.3 and Clang 8.0 when compiled with:

```
-std=c++17 -Wall -Wextra -pedantic
```

**Comment by sol-prog** [comment] 2019-04-15 20:23
I suppose both Clang/GCC will implicitly convert from path to string.

It seems that the only way to write truly portable C++ (or C) code is to test on all possible compiler/operating systems combinations. 

(As usual, Apple's Clang still doesn't provide the filesystem header or libc++fs library.)

**Comment by fenbf** [comment] 2019-04-17 08:07
in code there's a map of std::string and the path class has conversion operator:
https://en.cppreference.com/w/cpp/filesystem/path/native

but it converts to native string only... since GCC uses char/string for the representation then it works out of the box. On Windows we use wstring to store the path in the native format, so that's why extra conversion is needed.

so, to improve the "multiplatform'ity" it's probably better to declare map as:
std::unordered_map<filesystem::path::string_type, std::filesystem::file_time_type> paths_;

and also pass that type around rather than string. For the action callable object we could use filesystem::path, rather than string.
